class AppStrings {
  static const fieldCanNotBeEmpty = "Field can't be empty";
  static const addNewTaskNameHintText = "Task name";

  static const newTaskAdded = "New task added.";

  static const add = "Add";
  static const done = "Done";
  static const success = "success";
  static const newTask = "NEW TASK";
  static const icon = "Icon";
  static const name = "Name";
  static const login = "Login";
  static const userName = "Username";
  static const password = "Password";
  static const description = "Description";
  static const date = "Date";
  static const time = "Time";
  static const todo = "TODO";
  static const doneTasks = "DONE TASKS";
  static const noTasksFound = "No tasks found";
  static const updatedSuccessfully = "Updated Successfully.";
  static const loading = "Loading";
  static const ok = "Ok";
  static const retryAgain = "Try again";

  // error messages
  static const failedToAddTask = "Failed to add new task.";
  static const failedToGetTodoTasks = "Failed to get tasks.";
  static const errorHappened = "Error happened";
  static const noTaskWasUpdated = "No task was updated.";

  // error handler messages

  static const badRequestError = "bad request. try again later";
  static const noContent = "success with not content";
  static const forbiddenError = "forbidden request. try again later";
  static const unauthorizedError = "user unauthorized, try again later";
  static const notFoundError = "url not found, try again later";
  static const conflictError = "conflict found, try again later";
  static const internalServerError = "some thing went wrong, try again later";
  static const unknownError = "some thing went wrong, try again later";
  static const timeoutError = "time out, try again late";
  static const defaultError = "some thing went wrong, try again later";
  static const cacheError = "cache error, try again later";
  static const noInternetError = "Please check your internet connection";
}
